### ISSUE TITLE
特定の条件を持つ場合はカウントしないというフィルタが実装できるようにする

### ISSUE THREAD

**Issue by kuluna** [kuluna/EventGridView#18]
シフト表に休憩シフトを表示するとそれも人数分にカウントされてしまうという状態になるので、
この特定の条件の時はカウントしないというフィルタを自作できるインターフェースが欲しいです。

**Comment by bakatsuyuki** [comment]
EventにisNotCountみたいなフラグもってそれはカウントしない
でよいですか？

**Comment by kuluna** [comment]
カウンターをつけるかどうかは実装者の自由だけどモデルにはフラグを強制するというのはちょっとうーんな感じしますね

**Comment by kuluna** [comment]
くっそむずいのは休憩シフトを表示したことで、そこに重なる既存シフトもカウントしたくないとかそんなことが出て来そうな気がするんですよね。

**Comment by bakatsuyuki** [comment]
Eventに対してカウントするかどうかのフラグ持たないとすると、
`textColor` とか `text="休憩"` みたいな感じでフィルタするということでしょうか？
